# -*- ruby -*-

require 'rubygems'
require 'hoe'

# Hoe.plugin :compiler
# Hoe.plugin :cucumberfeatures
# Hoe.plugin :gem_prelude_sucks
# Hoe.plugin :inline
# Hoe.plugin :manifest
# Hoe.plugin :newgem
# Hoe.plugin :racc
# Hoe.plugin :rcov
# Hoe.plugin :rubyforge
# Hoe.plugin :website

Hoe.spec 'hello_hoe' do
  # HEY! If you fill these out in ~/.hoe_template/Rakefile.erb then
  # you'll never have to touch them again!
  # (delete this comment too, of course)

  # developer('FIX', 'FIX@example.com')

  # self.rubyforge_name = 'hello_hoex' # if different than 'hello_hoe'
end

# vim: syntax=ruby
